import {
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

/**
 * Engineerious data model.
 *
 * Three aggregated feeds (news | model | oss) all live in one `items` table so the
 * home page can rank them together with a single query. Blog posts live in MDX on
 * disk; `posts` is a thin mirror used only for repurposing/distribution bookkeeping.
 */

export const itemTypeEnum = pgEnum("item_type", ["news", "model", "oss"]);
export const itemStatusEnum = pgEnum("item_status", ["pending", "approved", "rejected"]);
export const repurposeStatusEnum = pgEnum("repurpose_status", [
  "pending_review",
  "approved",
  "scheduled",
  "published",
  "rejected",
  "failed",
]);
export const platformEnum = pgEnum("platform", [
  "linkedin",
  "x",
  "instagram",
  "youtube",
  "facebook",
]);
export const submissionStatusEnum = pgEnum("submission_status", [
  "pending",
  "accepted",
  "rejected",
]);

/**
 * One row per ingestion source. `weight` seeds authority into the ranking formula so
 * items rank sensibly before any human votes exist (see lib/ranking.ts).
 */
export const sources = pgTable(
  "sources",
  {
    id: serial("id").primaryKey(),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    type: itemTypeEnum("type").notNull(),
    adapter: text("adapter").notNull(),
    url: text("url"),
    weight: doublePrecision("weight").notNull().default(1),
    enabled: boolean("enabled").notNull().default(true),
    lastFetchedAt: timestamp("last_fetched_at", { withTimezone: true }),
    lastError: text("last_error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("sources_slug_key").on(t.slug)],
);

export const items = pgTable(
  "items",
  {
    id: serial("id").primaryKey(),
    type: itemTypeEnum("type").notNull(),
    status: itemStatusEnum("status").notNull().default("approved"),
    title: text("title").notNull(),
    url: text("url").notNull(),
    /** sha256 of the canonicalised URL — the dedupe key across overlapping feeds. */
    urlHash: text("url_hash").notNull(),
    summary: text("summary"),
    /** One-line "why it matters". Always rendered with an AI-generated label. */
    aiNote: text("ai_note"),
    source: text("source").notNull(),
    sourceSlug: text("source_slug").notNull(),
    sourceWeight: doublePrecision("source_weight").notNull().default(1),
    author: text("author"),
    points: integer("points").notNull().default(0),
    score: doublePrecision("score").notNull().default(0),
    firstSeen: timestamp("first_seen", { withTimezone: true }).notNull().defaultNow(),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    rankedAt: timestamp("ranked_at", { withTimezone: true }),
    rawJson: jsonb("raw_json"),
  },
  (t) => [
    uniqueIndex("items_url_hash_key").on(t.urlHash),
    index("items_type_score_idx").on(t.type, t.score),
    index("items_score_idx").on(t.score),
    index("items_published_idx").on(t.publishedAt),
    index("items_status_idx").on(t.status),
  ],
);

/**
 * Mirror of MDX frontmatter. Written on demand (see lib/content/blog.ts syncPost) so
 * repurpose jobs and distribution links have a stable FK. MDX on disk stays the
 * source of truth for the body.
 */
export const posts = pgTable(
  "posts",
  {
    id: serial("id").primaryKey(),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    dek: text("dek"),
    pillar: text("pillar").notNull(),
    canonical: text("canonical"),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    /** { linkedin: "https://...", x: "https://..." } — filled in after publishing. */
    distribution: jsonb("distribution").$type<Record<string, string>>().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("posts_slug_key").on(t.slug)],
);

export const repurposeJobs = pgTable(
  "repurpose_jobs",
  {
    id: serial("id").primaryKey(),
    postSlug: text("post_slug").notNull(),
    platform: platformEnum("platform").notNull(),
    status: repurposeStatusEnum("status").notNull().default("pending_review"),
    /** Platform-native draft body, generated by lib/repurpose. Human edits allowed. */
    draft: text("draft").notNull(),
    /** Carousel outlines, hooks, alt text — anything not part of the main body. */
    meta: jsonb("meta"),
    scheduledFor: timestamp("scheduled_for", { withTimezone: true }),
    publishedUrl: text("published_url"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("repurpose_jobs_post_platform_key").on(t.postSlug, t.platform),
    index("repurpose_jobs_status_idx").on(t.status),
  ],
);

export const submissions = pgTable(
  "submissions",
  {
    id: serial("id").primaryKey(),
    type: itemTypeEnum("type").notNull(),
    title: text("title").notNull(),
    url: text("url").notNull(),
    note: text("note"),
    submitterEmail: text("submitter_email"),
    status: submissionStatusEnum("status").notNull().default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("submissions_status_idx").on(t.status)],
);

export type Item = typeof items.$inferSelect;
export type NewItem = typeof items.$inferInsert;
export type Source = typeof sources.$inferSelect;
export type Post = typeof posts.$inferSelect;
export type RepurposeJob = typeof repurposeJobs.$inferSelect;
export type Submission = typeof submissions.$inferSelect;
export type ItemType = (typeof itemTypeEnum.enumValues)[number];
export type Platform = (typeof platformEnum.enumValues)[number];
